BubbleProfiler: BubbleProfiler::Generalized_fubini_potential Class Reference
BubbleProfiler::Generalized_fubini_potential Class Reference
#include <generalized_fubini_potential.hpp>
Public Member Functions
Generalized_fubini_potential ()=default
Generalized_fubini_potential (double, double, double)
virtual ~Generalized_fubini_potential ()=default
Generalized_fubini_potential (const Generalized_fubini_potential &)=default
Generalized_fubini_potential (Generalized_fubini_potential &&)=default
Generalized_fubini_potential & operator= (const Generalized_fubini_potential &)=default
Generalized_fubini_potential & operator= (Generalized_fubini_potential &&)=default
virtual Generalized_fubini_potential * clone () const override
Subclasses must implement a clone method.
virtual double operator() (const Eigen::VectorXd &) const override
Evaluate potential at point.
virtual double partial (const Eigen::VectorXd &, int) const override
Partial derivative WRT coordinate i at a point.
virtual double partial (const Eigen::VectorXd &, int, int) const override
Partial derivative WRT coordinates i, j at a a point.
virtual std::size_t get_number_of_fields () const override
virtual void translate_origin (const Eigen::VectorXd &translation) override
Shift the location of the origin by a specified vector.
virtual void apply_basis_change (const Eigen::MatrixXd &cob_matrix) override
Apply a change of basis matrix.
virtual void add_constant_term (double _offset) override
Add a constant offset to the potential.
double operator() (double) const
double first_deriv (double) const
double second_deriv (double) const
double get_local_minimum_location () const
double get_local_maximum_location () const
double get_bounce_solution_at (double) const
Field_profiles get_profile (const Eigen::VectorXd &) const
double get_action () const
Public Member Functions inherited from BubbleProfiler::Potential
virtual ~Potential ()=default
Private Attributes
double u {1.}
double v {1.}
double m {3.}
double origin {0.}
double scale {1.}
double offset {0.}
Detailed Description
Examples:
general_fubini.cpp.
Definition at line 28 of file generalized_fubini_potential.hpp.
Constructor & Destructor Documentation
BubbleProfiler::Generalized_fubini_potential::Generalized_fubini_potential () default
Referenced by clone().
BubbleProfiler::Generalized_fubini_potential::Generalized_fubini_potential (double u_, double v_, double m_)
Definition at line 24 of file generalized_fubini_potential.cpp.
References m, u, and v.
virtual BubbleProfiler::Generalized_fubini_potential::~Generalized_fubini_potential () virtual default
BubbleProfiler::Generalized_fubini_potential::Generalized_fubini_potential (const Generalized_fubini_potential &) default
BubbleProfiler::Generalized_fubini_potential::Generalized_fubini_potential (Generalized_fubini_potential &&) default
Member Function Documentation
virtual void BubbleProfiler::Generalized_fubini_potential::add_constant_term (double offset) inline override virtual
Add a constant offset to the potential.
Parameters
offset constant term to add to potential
Implements BubbleProfiler::Potential.
Definition at line 58 of file generalized_fubini_potential.hpp.
References first_deriv(), get_action(), get_bounce_solution_at(), get_local_maximum_location(), get_local_minimum_location(), get_profile(), offset, operator()(), and second_deriv().
virtual void BubbleProfiler::Generalized_fubini_potential::apply_basis_change (const Eigen::MatrixXd & cob_matrix) inline override virtual
Apply a change of basis matrix.
Parameters
cob_matrix
Implements BubbleProfiler::Potential.
Definition at line 54 of file generalized_fubini_potential.hpp.
References scale.
virtual Generalized_fubini_potential* BubbleProfiler::Generalized_fubini_potential::clone () const inline override virtual
Subclasses must implement a clone method.
Implements BubbleProfiler::Potential.
Definition at line 40 of file generalized_fubini_potential.hpp.
References Generalized_fubini_potential(), operator()(), and partial().
double BubbleProfiler::Generalized_fubini_potential::first_deriv (double coords) const
Definition at line 102 of file generalized_fubini_potential.cpp.
References BubbleProfiler::Abs(), m, origin, scale, u, and v.
Referenced by add_constant_term(), and partial().
double BubbleProfiler::Generalized_fubini_potential::get_action () const
Examples:
general_fubini.cpp.
Definition at line 154 of file generalized_fubini_potential.cpp.
References m, u, and v.
Referenced by add_constant_term(), and main().
double BubbleProfiler::Generalized_fubini_potential::get_bounce_solution_at (double r) const
Definition at line 136 of file generalized_fubini_potential.cpp.
References m, origin, scale, u, and v.
Referenced by add_constant_term(), and get_profile().
double BubbleProfiler::Generalized_fubini_potential::get_local_maximum_location () const
Definition at line 129 of file generalized_fubini_potential.cpp.
References m, origin, scale, and v.
Referenced by add_constant_term(), and BubbleProfiler::solve_shooting().
double BubbleProfiler::Generalized_fubini_potential::get_local_minimum_location () const
Examples:
general_fubini.cpp.
Definition at line 124 of file generalized_fubini_potential.cpp.
References origin, and scale.
Referenced by add_constant_term(), main(), BubbleProfiler::solve_perturbative(), and BubbleProfiler::solve_shooting().
virtual std::size_t BubbleProfiler::Generalized_fubini_potential::get_number_of_fields () const inline override virtual
Implements BubbleProfiler::Potential.
Definition at line 48 of file generalized_fubini_potential.hpp.
Field_profiles BubbleProfiler::Generalized_fubini_potential::get_profile (const Eigen::VectorXd & rho_values) const
Examples:
general_fubini.cpp.
Definition at line 142 of file generalized_fubini_potential.cpp.
References get_bounce_solution_at().
Referenced by add_constant_term(), main(), and BubbleProfiler::Generalized_fubini_observer::operator()().
double BubbleProfiler::Generalized_fubini_potential::operator() (const Eigen::VectorXd & coords) const override virtual
Evaluate potential at point.
Parameters
coords Coordinates at which to evaluate
Returns
Value of potential at coordinates
Implements BubbleProfiler::Potential.
Definition at line 40 of file generalized_fubini_potential.cpp.
Referenced by add_constant_term(), and clone().
double BubbleProfiler::Generalized_fubini_potential::operator() (double coords) const
Definition at line 91 of file generalized_fubini_potential.cpp.
References BubbleProfiler::Abs(), m, origin, scale, u, and v.
Generalized_fubini_potential& BubbleProfiler::Generalized_fubini_potential::operator= (const Generalized_fubini_potential &) default
Generalized_fubini_potential& BubbleProfiler::Generalized_fubini_potential::operator= (Generalized_fubini_potential &&) default
double BubbleProfiler::Generalized_fubini_potential::partial (const Eigen::VectorXd & coords, int i) const override virtual
Partial derivative WRT coordinate i at a point.
Parameters
coords Coordinates at which to evaluate
i Index of coordinate to be differentiated
Returns
Value of specified partial at point
Implements BubbleProfiler::Potential.
Definition at line 51 of file generalized_fubini_potential.cpp.
References first_deriv().
Referenced by clone().
double BubbleProfiler::Generalized_fubini_potential::partial (const Eigen::VectorXd & coords, int i, int j) const override virtual
Partial derivative WRT coordinates i, j at a a point.
Parameters
coords Coordinates at which to evaluate
i Index of first coordinate to be differentiated
j Index of second coordinate to be differentiated
Returns
Value of specified partial at point
Implements BubbleProfiler::Potential.
Definition at line 68 of file generalized_fubini_potential.cpp.
References second_deriv().
double BubbleProfiler::Generalized_fubini_potential::second_deriv (double coords) const
Definition at line 113 of file generalized_fubini_potential.cpp.
References BubbleProfiler::Abs(), m, origin, scale, u, and v.
Referenced by add_constant_term(), and partial().
virtual void BubbleProfiler::Generalized_fubini_potential::translate_origin (const Eigen::VectorXd & translation) inline override virtual
Shift the location of the origin by a specified vector.
Parameters
translation shift of origin
Implements BubbleProfiler::Potential.
Definition at line 50 of file generalized_fubini_potential.hpp.
References origin.
Member Data Documentation
double BubbleProfiler::Generalized_fubini_potential::m {3.} private
Definition at line 75 of file generalized_fubini_potential.hpp.
Referenced by first_deriv(), Generalized_fubini_potential(), get_action(), get_bounce_solution_at(), get_local_maximum_location(), operator()(), and second_deriv().
double BubbleProfiler::Generalized_fubini_potential::offset {0.} private
Definition at line 78 of file generalized_fubini_potential.hpp.
Referenced by add_constant_term().
double BubbleProfiler::Generalized_fubini_potential::origin {0.} private
Definition at line 76 of file generalized_fubini_potential.hpp.
Referenced by first_deriv(), get_bounce_solution_at(), get_local_maximum_location(), get_local_minimum_location(), operator()(), second_deriv(), and translate_origin().
double BubbleProfiler::Generalized_fubini_potential::scale {1.} private
Definition at line 77 of file generalized_fubini_potential.hpp.
Referenced by apply_basis_change(), first_deriv(), get_bounce_solution_at(), get_local_maximum_location(), get_local_minimum_location(), operator()(), and second_deriv().
double BubbleProfiler::Generalized_fubini_potential::u {1.} private
Definition at line 73 of file generalized_fubini_potential.hpp.
Referenced by first_deriv(), Generalized_fubini_potential(), get_action(), get_bounce_solution_at(), operator()(), and second_deriv().
double BubbleProfiler::Generalized_fubini_potential::v {1.} private
Definition at line 74 of file generalized_fubini_potential.hpp.
Referenced by first_deriv(), Generalized_fubini_potential(), get_action(), get_bounce_solution_at(), get_local_maximum_location(), operator()(), and second_deriv().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/examples/general-fubini/generalized_fubini_potential.hpp
/home/michael/bubbleprofiler_release/examples/general-fubini/generalized_fubini_potential.cpp