BubbleProfiler: BubbleProfiler::logging::Basic_logger Class Reference
BubbleProfiler::logging::Basic_logger Class Reference
#include <basic_logger.hpp>
Public Member Functions
void log_message (Log_level level, const std::string &msg) const
Detailed Description
Definition at line 28 of file basic_logger.hpp.
Member Function Documentation
void BubbleProfiler::logging::Basic_logger::log_message (Log_level level, const std::string & msg) const
Definition at line 24 of file basic_logger.cpp.
References BubbleProfiler::logging::Logging_manager::get_manager(), and BubbleProfiler::logging::Logging_manager::log().
Referenced by BubbleProfiler::Algebraic_potential::add_constant_term(), BubbleProfiler::Algebraic_potential::Algebraic_potential(), BubbleProfiler::Algebraic_potential::apply_basis_change(), BubbleProfiler::Perturbative_profiler< Integration_policy >::calculate_bubble_profile(), BubbleProfiler::Shooting_profile_guesser::calculate_potential_parameters(), BubbleProfiler::Kink_profile_guesser::calculate_potential_parameters(), BubbleProfiler::Relative_convergence_tester::check_action_converged(), BubbleProfiler::Relative_convergence_tester::check_fields_converged(), BubbleProfiler::Kink_profile_guesser::fit_ansatz_parameters(), BubbleProfiler::Kink_profile_guesser::guess_domain_end(), BubbleProfiler::Kink_profile_guesser::guess_domain_start(), BubbleProfiler::Relative_convergence_tester::is_converged(), BubbleProfiler::Instream_profile_guesser::read_profiles(), BubbleProfiler::Algebraic_potential::translate_origin(), BubbleProfiler::Profile_observer::write_action_to_file(), and BubbleProfiler::Profile_observer::write_initial_profiles_to_file().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/include/basic_logger.hpp
/home/michael/bubbleprofiler_release/src/basic_logger.cpp