BubbleProfiler: BubbleProfiler::logging::Logging_manager Class Reference
BubbleProfiler::logging::Logging_manager Class Reference
#include <logging_manager.hpp>
Public Member Functions
Logging_manager (const Logging_manager &)=delete
Logging_manager (Logging_manager &&)=delete
Logging_manager & operator= (const Logging_manager &)=delete
Logging_manager & operator= (Logging_manager &&)=delete
void set_logging_enabled (bool flag)
void set_minimum_log_level (Log_level level)
void log (const Log_message &message)
Static Public Member Functions
static Logging_manager & get_manager ()
Protected Member Functions
Logging_manager ()=default
~Logging_manager ()=default
Private Member Functions
bool above_min_level (Log_level) const
Private Attributes
bool logging_enabled {true}
Log_level min_level {Log_level::Warning}
Detailed Description
Definition at line 27 of file logging_manager.hpp.
Constructor & Destructor Documentation
BubbleProfiler::logging::Logging_manager::Logging_manager (const Logging_manager &) delete
BubbleProfiler::logging::Logging_manager::Logging_manager (Logging_manager &&) delete
BubbleProfiler::logging::Logging_manager::Logging_manager () protected default
Referenced by set_minimum_log_level().
BubbleProfiler::logging::Logging_manager::~Logging_manager () protected default
Referenced by set_minimum_log_level().
Member Function Documentation
bool BubbleProfiler::logging::Logging_manager::above_min_level (Log_level level) const private
Definition at line 34 of file logging_manager.cpp.
References BubbleProfiler::logging::Debug, BubbleProfiler::logging::Error, BubbleProfiler::logging::Fatal, BubbleProfiler::logging::Info, min_level, BubbleProfiler::logging::Trace, and BubbleProfiler::logging::Warning.
Referenced by log().
Logging_manager & BubbleProfiler::logging::Logging_manager::get_manager () static
Examples:
action.cpp, general_fubini.cpp, logarithmic.cpp, scale.cpp, tabulate.cpp, and thin_wall.cpp.
Definition at line 27 of file logging_manager.cpp.
Referenced by BubbleProfiler::configure_logging(), BubbleProfiler::logging::Basic_logger::log_message(), and main().
void BubbleProfiler::logging::Logging_manager::log (const Log_message & message)
Definition at line 83 of file logging_manager.cpp.
References above_min_level(), BubbleProfiler::logging::Log_message::get_log_entry(), BubbleProfiler::logging::Log_message::get_log_level(), and logging_enabled.
Referenced by BubbleProfiler::logging::Basic_logger::log_message(), and set_minimum_log_level().
Logging_manager& BubbleProfiler::logging::Logging_manager::operator= (const Logging_manager &) delete
Logging_manager& BubbleProfiler::logging::Logging_manager::operator= (Logging_manager &&) delete
void BubbleProfiler::logging::Logging_manager::set_logging_enabled (bool flag) inline
Definition at line 36 of file logging_manager.hpp.
References logging_enabled.
void BubbleProfiler::logging::Logging_manager::set_minimum_log_level (Log_level level) inline
Examples:
action.cpp, general_fubini.cpp, logarithmic.cpp, scale.cpp, tabulate.cpp, and thin_wall.cpp.
Definition at line 37 of file logging_manager.hpp.
References log(), Logging_manager(), min_level, and ~Logging_manager().
Referenced by main().
Member Data Documentation
bool BubbleProfiler::logging::Logging_manager::logging_enabled {true} private
Definition at line 46 of file logging_manager.hpp.
Referenced by log(), and set_logging_enabled().
Log_level BubbleProfiler::logging::Logging_manager::min_level {Log_level::Warning} private
Definition at line 47 of file logging_manager.hpp.
Referenced by above_min_level(), and set_minimum_log_level().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/include/logging_manager.hpp
/home/michael/bubbleprofiler_release/src/logging_manager.cpp