BubbleProfiler: BubbleProfiler::Thin_wall_observer Class Reference
BubbleProfiler::Thin_wall_observer Class Reference
#include <thin_wall_observer.hpp>
Public Member Functions
Thin_wall_observer (const std::string &output_file_)
void operator() (const Field_profiles &profile, const Field_profiles &perturbation)
Private Member Functions
void write_file_header ()
void write_data (const Field_profiles &, const Field_profiles &)
Private Attributes
int iteration_count {0}
std::string output_file {}
std::ofstream output_stream
Detailed Description
Definition at line 28 of file thin_wall_observer.hpp.
Constructor & Destructor Documentation
BubbleProfiler::Thin_wall_observer::Thin_wall_observer (const std::string & output_file_) explicit
Definition at line 26 of file thin_wall_observer.cpp.
References output_file, and output_stream.
Member Function Documentation
void BubbleProfiler::Thin_wall_observer::operator() (const Field_profiles & profile, const Field_profiles & perturbation)
Definition at line 70 of file thin_wall_observer.cpp.
References iteration_count, write_data(), and write_file_header().
void BubbleProfiler::Thin_wall_observer::write_data (const Field_profiles & profile, const Field_profiles & perturbation) private
Definition at line 46 of file thin_wall_observer.cpp.
References BubbleProfiler::Field_profiles::get_field_profiles(), BubbleProfiler::Field_profiles::get_spatial_grid(), iteration_count, output_file, and output_stream.
Referenced by operator()().
void BubbleProfiler::Thin_wall_observer::write_file_header () private
Definition at line 33 of file thin_wall_observer.cpp.
References output_file, and output_stream.
Referenced by operator()().
Member Data Documentation
int BubbleProfiler::Thin_wall_observer::iteration_count {0} private
Definition at line 35 of file thin_wall_observer.hpp.
Referenced by operator()(), and write_data().
std::string BubbleProfiler::Thin_wall_observer::output_file {} private
Definition at line 36 of file thin_wall_observer.hpp.
Referenced by Thin_wall_observer(), write_data(), and write_file_header().
std::ofstream BubbleProfiler::Thin_wall_observer::output_stream private
Definition at line 37 of file thin_wall_observer.hpp.
Referenced by Thin_wall_observer(), write_data(), and write_file_header().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/examples/thin-wall/thin_wall_observer.hpp
/home/michael/bubbleprofiler_release/examples/thin-wall/thin_wall_observer.cpp