BubbleProfiler: BubbleProfiler::Generalized_fubini_observer Class Reference
BubbleProfiler::Generalized_fubini_observer Class Reference
#include <generalized_fubini_observer.hpp>
Public Member Functions
Generalized_fubini_observer (const Generalized_fubini_potential &potential_, const std::string &output_file_)
void operator() (const Field_profiles &profile, const Field_profiles &perturbation)
Private Member Functions
void write_file_header ()
void write_data (const Field_profiles &, const Field_profiles &, const Field_profiles &)
Private Attributes
int iteration_count {0}
Generalized_fubini_potential potential {}
std::string output_file {}
std::ofstream output_stream
Detailed Description
Definition at line 30 of file generalized_fubini_observer.hpp.
Constructor & Destructor Documentation
BubbleProfiler::Generalized_fubini_observer::Generalized_fubini_observer (const Generalized_fubini_potential & potential_, const std::string & output_file_)
Definition at line 26 of file generalized_fubini_observer.cpp.
References output_file, and output_stream.
Member Function Documentation
void BubbleProfiler::Generalized_fubini_observer::operator() (const Field_profiles & profile, const Field_profiles & perturbation)
Definition at line 77 of file generalized_fubini_observer.cpp.
References BubbleProfiler::Generalized_fubini_potential::get_profile(), BubbleProfiler::Field_profiles::get_spatial_grid(), iteration_count, potential, write_data(), and write_file_header().
void BubbleProfiler::Generalized_fubini_observer::write_data (const Field_profiles & profile, const Field_profiles & perturbation, const Field_profiles & exact) private
Definition at line 49 of file generalized_fubini_observer.cpp.
References BubbleProfiler::Field_profiles::get_field_profiles(), BubbleProfiler::Field_profiles::get_spatial_grid(), iteration_count, output_file, and output_stream.
Referenced by operator()().
void BubbleProfiler::Generalized_fubini_observer::write_file_header () private
Definition at line 35 of file generalized_fubini_observer.cpp.
References output_file, and output_stream.
Referenced by operator()().
Member Data Documentation
int BubbleProfiler::Generalized_fubini_observer::iteration_count {0} private
Definition at line 38 of file generalized_fubini_observer.hpp.
Referenced by operator()(), and write_data().
std::string BubbleProfiler::Generalized_fubini_observer::output_file {} private
Definition at line 40 of file generalized_fubini_observer.hpp.
Referenced by Generalized_fubini_observer(), write_data(), and write_file_header().
std::ofstream BubbleProfiler::Generalized_fubini_observer::output_stream private
Definition at line 41 of file generalized_fubini_observer.hpp.
Referenced by Generalized_fubini_observer(), write_data(), and write_file_header().
Generalized_fubini_potential BubbleProfiler::Generalized_fubini_observer::potential {} private
Definition at line 39 of file generalized_fubini_observer.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/examples/general-fubini/generalized_fubini_observer.hpp
/home/michael/bubbleprofiler_release/examples/general-fubini/generalized_fubini_observer.cpp