BubbleProfiler: BubbleProfiler::logging::Default_log_message Class Reference
BubbleProfiler::logging::Default_log_message Class Reference
#include <log_message.hpp>
Public Member Functions
Default_log_message (Log_level level_, const std::string &message_)
virtual ~Default_log_message ()=default
Log_level get_log_level () const override
std::string get_log_entry () const override
Public Member Functions inherited from BubbleProfiler::logging::Log_message
virtual ~Log_message ()=default
Private Types
using Clock = std::chrono::system_clock
using Time = std::chrono::time_point< Clock >
Private Member Functions
std::string get_formatted_time () const
Private Attributes
Log_level level {Log_level::Trace}
std::string message {}
Time log_time {Clock::now()}
Detailed Description
Definition at line 40 of file log_message.hpp.
Member Typedef Documentation
using BubbleProfiler::logging::Default_log_message::Clock = std::chrono::system_clock private
Definition at line 50 of file log_message.hpp.
using BubbleProfiler::logging::Default_log_message::Time = std::chrono::time_point<Clock> private
Definition at line 51 of file log_message.hpp.
Constructor & Destructor Documentation
BubbleProfiler::logging::Default_log_message::Default_log_message (Log_level level_, const std::string & message_) inline
Definition at line 42 of file log_message.hpp.
virtual BubbleProfiler::logging::Default_log_message::~Default_log_message () virtual default
Member Function Documentation
std::string BubbleProfiler::logging::Default_log_message::get_formatted_time () const private
Definition at line 43 of file log_message.cpp.
References log_time.
Referenced by get_log_entry().
std::string BubbleProfiler::logging::Default_log_message::get_log_entry () const override virtual
Implements BubbleProfiler::logging::Log_message.
Definition at line 53 of file log_message.cpp.
References get_formatted_time(), level, message, and BubbleProfiler::logging::to_log_level_string().
Log_level BubbleProfiler::logging::Default_log_message::get_log_level () const inline override virtual
Implements BubbleProfiler::logging::Log_message.
Definition at line 46 of file log_message.hpp.
Member Data Documentation
Log_level BubbleProfiler::logging::Default_log_message::level {Log_level::Trace} private
Definition at line 53 of file log_message.hpp.
Referenced by get_log_entry().
Time BubbleProfiler::logging::Default_log_message::log_time {Clock::now()} private
Definition at line 55 of file log_message.hpp.
Referenced by get_formatted_time().
std::string BubbleProfiler::logging::Default_log_message::message {} private
Definition at line 54 of file log_message.hpp.
Referenced by get_log_entry().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/include/log_message.hpp
/home/michael/bubbleprofiler_release/src/log_message.cpp