BubbleProfiler: BubbleProfiler::Logarithmic_observer Class Reference
BubbleProfiler::Logarithmic_observer Class Reference
#include <logarithmic_observer.hpp>
Public Member Functions
Logarithmic_observer (const Logarithmic_potential &potential_, const std::string &output_file_)
void operator() (const Field_profiles &profile, const Field_profiles &perturbation)
Private Member Functions
void write_file_header ()
void write_data (const Field_profiles &, const Field_profiles &, const Field_profiles &)
Private Attributes
int iteration_count {0}
Logarithmic_potential potential {}
std::string output_file {}
std::ofstream output_stream
Detailed Description
Definition at line 30 of file logarithmic_observer.hpp.
Constructor & Destructor Documentation
BubbleProfiler::Logarithmic_observer::Logarithmic_observer (const Logarithmic_potential & potential_, const std::string & output_file_)
Definition at line 26 of file logarithmic_observer.cpp.
References output_file, and output_stream.
Member Function Documentation
void BubbleProfiler::Logarithmic_observer::operator() (const Field_profiles & profile, const Field_profiles & perturbation)
Definition at line 77 of file logarithmic_observer.cpp.
References BubbleProfiler::Logarithmic_potential::get_profile(), BubbleProfiler::Field_profiles::get_spatial_grid(), iteration_count, potential, write_data(), and write_file_header().
void BubbleProfiler::Logarithmic_observer::write_data (const Field_profiles & profile, const Field_profiles & perturbation, const Field_profiles & exact) private
Definition at line 49 of file logarithmic_observer.cpp.
References BubbleProfiler::Field_profiles::get_field_profiles(), BubbleProfiler::Field_profiles::get_spatial_grid(), iteration_count, output_file, and output_stream.
Referenced by operator()().
void BubbleProfiler::Logarithmic_observer::write_file_header () private
Definition at line 35 of file logarithmic_observer.cpp.
References output_file, and output_stream.
Referenced by operator()().
Member Data Documentation
int BubbleProfiler::Logarithmic_observer::iteration_count {0} private
Definition at line 38 of file logarithmic_observer.hpp.
Referenced by operator()(), and write_data().
std::string BubbleProfiler::Logarithmic_observer::output_file {} private
Definition at line 40 of file logarithmic_observer.hpp.
Referenced by Logarithmic_observer(), write_data(), and write_file_header().
std::ofstream BubbleProfiler::Logarithmic_observer::output_stream private
Definition at line 41 of file logarithmic_observer.hpp.
Referenced by Logarithmic_observer(), write_data(), and write_file_header().
Logarithmic_potential BubbleProfiler::Logarithmic_observer::potential {} private
Definition at line 39 of file logarithmic_observer.hpp.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/michael/bubbleprofiler_release/examples/logarithmic/logarithmic_observer.hpp
/home/michael/bubbleprofiler_release/examples/logarithmic/logarithmic_observer.cpp