BubbleProfiler: /home/michael/bubbleprofiler_release/examples/quartic/action.cpp File Reference
action.cpp File Reference
Program that calculates action for a one-dimensional potential parameterized by \(E\) and \(\alpha\).
#include "error.hpp"
#include "logging_manager.hpp"
#include "restricted_quartic_potential.hpp"
#include "shooting.hpp"
#include <iostream>
#include <string>
#include <vector>
Classes
struct BubbleProfiler::Action_options
Namespaces
BubbleProfiler
Functions
void BubbleProfiler::print_usage ()
bool BubbleProfiler::starts_with (const std::string &option, const std::string &prefix)
void BubbleProfiler::parse_positional_args (const std::vector< std::string > &args, Action_options &options)
Bubble_profiler_inputs BubbleProfiler::parse_cmd_line_args (int argc, const char *argv[])
int main (int argc, const char *argv[])
Detailed Description
Program that calculates action for a one-dimensional potential parameterized by \(E\) and \(\alpha\).
The potential is
\[ V(\phi) = E\left[\frac{-4 \alpha +3}{2} \phi^2 - \phi ^3 + \alpha \phi ^4\right]. \]
Usage:
./action <E> <alpha> <dim>
Definition in file action.cpp.
Function Documentation
int main (int argc, const char * argv[])
Examples:
action.cpp.
Definition at line 147 of file action.cpp.
References BubbleProfiler::Action_options::alpha, BubbleProfiler::Action_options::dim, BubbleProfiler::Action_options::E, BubbleProfiler::Shooting::get_euclidean_action(), BubbleProfiler::Restricted_quartic_potential::get_global_minimum_location(), BubbleProfiler::Restricted_quartic_potential::get_local_maximum_location(), BubbleProfiler::Restricted_quartic_potential::get_local_minimum_location(), BubbleProfiler::logging::Logging_manager::get_manager(), BubbleProfiler::parse_cmd_line_args(), BubbleProfiler::Shooting::set_action_abs_tol(), BubbleProfiler::Shooting::set_action_arrived_rel(), BubbleProfiler::Shooting::set_action_rel_tol(), BubbleProfiler::Shooting::set_bisect_lambda_max(), BubbleProfiler::Shooting::set_bisection_precision_bits(), BubbleProfiler::Shooting::set_drho_frac(), BubbleProfiler::Shooting::set_f_y_max(), BubbleProfiler::Shooting::set_f_y_min(), BubbleProfiler::Shooting::set_max_iterations(), BubbleProfiler::Shooting::set_max_periods(), BubbleProfiler::logging::Logging_manager::set_minimum_log_level(), BubbleProfiler::Shooting::set_shooting_abs_tol(), BubbleProfiler::Shooting::set_shooting_rel_tol(), BubbleProfiler::Shooting::set_y_max(), BubbleProfiler::Shooting::solve(), BubbleProfiler::logging::Trace, and BubbleProfiler::Action_options::verbose.