BubbleProfiler: /home/michael/bubbleprofiler_release/examples/logarithmic/logarithmic.cpp File Reference
logarithmic.cpp File Reference
Program that calculates action for a one-dimensional potential in case in which exact solution is known (the logarithmic potential).
#include "error.hpp"
#include "field_profiles.hpp"
#include "gsl_root_finder.hpp"
#include "kink_profile_guesser.hpp"
#include "logarithmic_potential.hpp"
#include "logging_manager.hpp"
#include "logarithmic_observer.hpp"
#include "perturbative_profiler.hpp"
#include "shooting.hpp"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <tuple>
#include <vector>
Classes
struct BubbleProfiler::Logarithmic_options
Namespaces
BubbleProfiler
Functions
void BubbleProfiler::print_usage ()
bool BubbleProfiler::starts_with (const std::string &option, const std::string &prefix)
std::string BubbleProfiler::get_option_value (const std::string &option, const std::string &sep="=")
void BubbleProfiler::parse_positional_args (const std::vector< std::string > &args, Logarithmic_options &options)
double BubbleProfiler::parse_global_min (const std::string &value)
Bubble_profiler_inputs BubbleProfiler::parse_cmd_line_args (int argc, const char *argv[])
std::tuple< double, Field_profiles > BubbleProfiler::solve_shooting (const Logarithmic_potential &potential, double true_min, bool calculate_profile)
std::tuple< double, Field_profiles > BubbleProfiler::solve_perturbative (Logarithmic_potential &potential, double true_min, const std::string &observer_file)
void BubbleProfiler::write_profile (std::ostream &ostr, const Field_profiles &numerical_profile, const Field_profiles &exact_profile)
void BubbleProfiler::write_action (std::ostream &ostr, double numerical_action, double exact_action)
int main (int argc, const char *argv[])
Detailed Description
Program that calculates action for a one-dimensional potential in case in which exact solution is known (the logarithmic potential).
The potential is (see Eq. (8) of https://arxiv.org/abs/1412.3160)
\[ V(\phi) = \frac12 m^2 \phi^2 \left[1 - \ln \left(\frac{\phi^2}{w^2}\right) \right]. \]
Usage:
./logarithmic <m> <w>
Definition in file logarithmic.cpp.
Function Documentation
int main (int argc, const char * argv[])
Examples:
logarithmic.cpp.
Definition at line 392 of file logarithmic.cpp.
References Eigen::abs(), BubbleProfiler::Logarithmic_options::calculate_profile, BubbleProfiler::Logarithmic_potential::get_action(), BubbleProfiler::Logarithmic_potential::get_local_minimum_location(), BubbleProfiler::logging::Logging_manager::get_manager(), BubbleProfiler::Logarithmic_potential::get_profile(), BubbleProfiler::Field_profiles::get_spatial_grid(), BubbleProfiler::Logarithmic_options::global_min, BubbleProfiler::Logarithmic_options::m, BubbleProfiler::Logarithmic_options::output_file, BubbleProfiler::parse_cmd_line_args(), BubbleProfiler::Logarithmic_options::perturbations_file, BubbleProfiler::logging::Logging_manager::set_minimum_log_level(), BubbleProfiler::solve_perturbative(), BubbleProfiler::solve_shooting(), BubbleProfiler::logging::Trace, BubbleProfiler::Logarithmic_options::use_perturbative, BubbleProfiler::Logarithmic_options::verbose, BubbleProfiler::Logarithmic_options::w, BubbleProfiler::write_action(), and BubbleProfiler::write_profile().