BubbleProfiler: /home/michael/bubbleprofiler_release/src/run_cmd_line_potential.cpp File Reference
run_cmd_line_potential.cpp File Reference
Command line interface to BubbleProfiler
#include "error.hpp"
#include "gsl_root_finder.hpp"
#include "instream_profile_guesser.hpp"
#include "kink_profile_guesser.hpp"
#include "logging_manager.hpp"
#include "nlopt_optimizer.hpp"
#include "observers.hpp"
#include "perturbative_profiler.hpp"
#include "potential.hpp"
#include "relative_convergence_tester.hpp"
#include "shooting.hpp"
#include "shooting_profile_guesser.hpp"
#include "algebraic_potential.hpp"
#include <boost/program_options.hpp>
#include <boost/filesystem.hpp>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
Classes
struct BubbleProfiler::Bubble_profiler_inputs
Namespaces
BubbleProfiler
Enumerations
enum BubbleProfiler::Integration_algorithm : int { BubbleProfiler::Integration_algorithm::Runge_kutta_4 = 0, BubbleProfiler::Integration_algorithm::Euler }
Functions
void BubbleProfiler::validate (boost::any &v, const std::vector< std::string > &values, Integration_algorithm *, int)
Bubble_profiler_inputs BubbleProfiler::parse_cmd_line_args (int argc, const char *argv[])
void BubbleProfiler::write_action (double action, std::ostream &ostr)
Write the value of the action to requested output stream.
void BubbleProfiler::write_profiles (const std::vector< std::string > &fields, const Field_profiles &profiles, std::ostream &ostr)
Write the given field profiles to requested output stream.
Eigen::VectorXd BubbleProfiler::find_global_min (const Potential &potential, double opt_timeout)
Find the global minimum of the given potential.
Eigen::VectorXd BubbleProfiler::find_one_dimensional_barrier (const Potential &potential, const Eigen::VectorXd &true_vacuum_loc, const Eigen::VectorXd &false_vacuum_loc, double opt_timeout)
Find barrier directly between two minima of a 1D potential.
void BubbleProfiler::initialize_extrema (const Potential &potential, const Bubble_profiler_inputs &input, Eigen::VectorXd &true_vacuum_loc, Eigen::VectorXd &false_vacuum_loc)
Locate the requested critical points if not already provided.
void BubbleProfiler::initialize_extrema (const Potential &potential, const Bubble_profiler_inputs &input, Eigen::VectorXd &true_vacuum_loc, Eigen::VectorXd &false_vacuum_loc, Eigen::VectorXd &barrier_loc)
Locate the necessary critical points if not already provided.
std::tuple< double, Field_profiles > BubbleProfiler::run_shooting_profiler (const Bubble_profiler_inputs &input)
Calculates the action and bubble profile using the shooting method.
template<class Profiler >
std::tuple< double, Field_profiles > BubbleProfiler::run_perturbative_profiler (const Bubble_profiler_inputs &input, Profiler &profiler)
Calculates the action and bubble profile using the perturbative method.
std::tuple< double, Field_profiles > BubbleProfiler::run_perturbative_profiler (const Bubble_profiler_inputs &input)
Calculates the action and bubble profile using the perturbative method.
void BubbleProfiler::run_profiler (const Bubble_profiler_inputs &input)
Calculates the action and bubble profile for the given potential.
void BubbleProfiler::configure_logging (const Bubble_profiler_inputs &input)
int main (int argc, const char *argv[])
Variables
const std::string BubbleProfiler::default_ansatz_file = ""
const double BubbleProfiler::default_domain_start = -1.
const double BubbleProfiler::default_domain_end = -1.
const double BubbleProfiler::default_initial_step_size = 1.e-2
const int BubbleProfiler::default_interp_fraction = 1.0
const Integration_algorithm BubbleProfiler::default_algorithm
const double BubbleProfiler::default_rtol_action = 1.e-3
const double BubbleProfiler::default_rtol_fields = 1.e-3
const std::string BubbleProfiler::default_output_file = "-"
const bool BubbleProfiler::default_write_perturbations = true
const bool BubbleProfiler::default_force_output = false
const double BubbleProfiler::default_opt_timeout = 10.
const int BubbleProfiler::default_max_iterations = -1
const bool BubbleProfiler::default_assume_origin_false_vacuum = false
const bool BubbleProfiler::default_use_perturbative = false
const bool BubbleProfiler::default_write_profiles = false
const bool BubbleProfiler::default_shooting_ansatz = false
const bool BubbleProfiler::default_verbose = false
const int BubbleProfiler::default_shoot_bisect_bits = 5
const double BubbleProfiler::default_action_arrived_rel = 1.e-3
const double BubbleProfiler::default_shoot_ode_abs = 1.e-4
const double BubbleProfiler::default_shoot_ode_rel = 1.e-4
const double BubbleProfiler::default_action_ode_abs = 1.e-6
const double BubbleProfiler::default_action_ode_rel = 1.e-6
const double BubbleProfiler::default_drho_frac = 1.e-3
const double BubbleProfiler::default_evolve_change_rel = 1.e-2
const double BubbleProfiler::default_bisect_lambda_max = 5.0
const int BubbleProfiler::default_iter_max = 100000
const double BubbleProfiler::default_periods_max = 1.e2
const double BubbleProfiler::default_f_y_max = 1.e6
const double BubbleProfiler::default_f_y_min = 1.e-3
const double BubbleProfiler::default_y_max = 1.e1
Detailed Description
Command line interface to BubbleProfiler
Todo:
Usage, e.g.,
./BubbleProfiler
Definition in file run_cmd_line_potential.cpp.
Function Documentation
int main (int argc, const char * argv[])
Definition at line 733 of file run_cmd_line_potential.cpp.
References BubbleProfiler::configure_logging(), BubbleProfiler::Bubble_profiler_inputs::fields, BubbleProfiler::Bubble_profiler_inputs::force_output, plot_tabulate_results::output_file, BubbleProfiler::Bubble_profiler_inputs::output_file, BubbleProfiler::Bubble_profiler_inputs::output_path, BubbleProfiler::parse_cmd_line_args(), BubbleProfiler::Bubble_profiler_inputs::potential, and BubbleProfiler::run_profiler().