BubbleProfiler: /home/michael/bubbleprofiler_release/src/action.cpp File Reference
action.cpp File Reference
Functions for calculating action for one-dimensional potential parameterized by \(E\) and \(\alpha\).
#include "action.hpp"
#include "shooting.hpp"
Functions
double action (const double E, const double alpha, const int dim, BubbleProfiler::Shooting_settings settings)
Detailed Description
Functions for calculating action for one-dimensional potential parameterized by \(E\) and \(\alpha\).
The potential is
\[ V(\phi) = E\left[\frac{-4 \alpha +3}{2} \phi^2 - \phi ^3 + \alpha \phi ^4\right]. \]
We must construct potentials etc for particular \(E\) and \(\alpha\) and pass them to the Shooting class.
Definition in file action.cpp.
Function Documentation
double action (const double E, const double alpha, const int dim, BubbleProfiler::Shooting_settings settings)
Returns
Action, \(S\)
Parameters
E \(E\)
alpha \(\alpha\)
dim Number of space-time dimensions, \(d\)
settings Settings for solver
Definition at line 35 of file action.cpp.
References BubbleProfiler::Shooting_settings::action_arrived_rel, BubbleProfiler::Shooting_settings::action_ode_abs, BubbleProfiler::Shooting_settings::action_ode_rel, gaussian_alpha_tests::alpha, BubbleProfiler::Shooting_settings::bisect_lambda_max, BubbleProfiler::Shooting_settings::drho_frac, pyshooting::E, BubbleProfiler::Shooting_settings::f_y_max, BubbleProfiler::Shooting_settings::f_y_min, BubbleProfiler::Shooting::get_euclidean_action(), BubbleProfiler::Shooting_settings::iter_max, BubbleProfiler::Shooting_settings::periods_max, BubbleProfiler::Shooting::set_action_abs_tol(), BubbleProfiler::Shooting::set_action_arrived_rel(), BubbleProfiler::Shooting::set_action_rel_tol(), BubbleProfiler::Shooting::set_bisect_lambda_max(), BubbleProfiler::Shooting::set_bisection_precision_bits(), BubbleProfiler::Shooting::set_drho_frac(), BubbleProfiler::Shooting::set_f_y_max(), BubbleProfiler::Shooting::set_f_y_min(), BubbleProfiler::Shooting::set_max_iterations(), BubbleProfiler::Shooting::set_max_periods(), BubbleProfiler::Shooting::set_shooting_abs_tol(), BubbleProfiler::Shooting::set_shooting_rel_tol(), BubbleProfiler::Shooting::set_y_max(), BubbleProfiler::Shooting_settings::shoot_bisect_bits, BubbleProfiler::Shooting_settings::shoot_ode_abs, BubbleProfiler::Shooting_settings::shoot_ode_rel, BubbleProfiler::Shooting::solve(), and BubbleProfiler::Shooting_settings::y_max.