BubbleProfiler: /home/michael/bubbleprofiler_release/examples/thin-wall/thin_wall.cpp File Reference
thin_wall.cpp File Reference
Program that calculates action for a one-dimensional potential in a thin-wall case, in which exact solution is known.
#include "error.hpp"
#include "field_profiles.hpp"
#include "gsl_root_finder.hpp"
#include "kink_profile_guesser.hpp"
#include "logging_manager.hpp"
#include "perturbative_profiler.hpp"
#include "shooting.hpp"
#include "thin_wall_observer.hpp"
#include "thin_wall_potential.hpp"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <tuple>
#include <vector>
Classes
struct BubbleProfiler::Thin_wall_options
Namespaces
BubbleProfiler
Functions
void BubbleProfiler::print_usage ()
bool BubbleProfiler::starts_with (const std::string &option, const std::string &prefix)
std::string BubbleProfiler::get_option_value (const std::string &option, const std::string &sep="=")
void BubbleProfiler::parse_positional_args (const std::vector< std::string > &args, Thin_wall_options &options)
Bubble_profiler_inputs BubbleProfiler::parse_cmd_line_args (int argc, const char *argv[])
std::tuple< double, Field_profiles > BubbleProfiler::solve_shooting (const Thin_wall_potential &potential, int dim, bool calculate_profile)
std::tuple< double, Field_profiles > BubbleProfiler::solve_perturbative (Thin_wall_potential &potential, int dim, const std::string &observer_file)
void BubbleProfiler::write_profile (std::ostream &ostr, const Field_profiles &numerical_profile)
void BubbleProfiler::write_action (std::ostream &ostr, double numerical_action, double exact_action)
int main (int argc, const char *argv[])
Detailed Description
Program that calculates action for a one-dimensional potential in a thin-wall case, in which exact solution is known.
The potential is (see Eq. (4.5) of https://journals.aps.org/prd/pdf/10.1103/PhysRevD.15.2929)
\[ V(\phi) = \frac{\lambda}{8} (\phi^2 - a^2)^2 + \frac{\epsilon}{2 a} (\phi - a). \]
Usage:
./thin <lambda> <a> <delta>
Definition in file thin_wall.cpp.
Function Documentation
int main (int argc, const char * argv[])
Examples:
thin_wall.cpp.
Definition at line 364 of file thin_wall.cpp.
References BubbleProfiler::Thin_wall_options::a, BubbleProfiler::Thin_wall_options::calculate_profile, BubbleProfiler::Thin_wall_options::delta, BubbleProfiler::Thin_wall_options::dim, BubbleProfiler::logging::Logging_manager::get_manager(), BubbleProfiler::Thin_wall_potential::get_thin_wall_action(), BubbleProfiler::Thin_wall_options::lambda, BubbleProfiler::Thin_wall_options::output_file, BubbleProfiler::parse_cmd_line_args(), BubbleProfiler::Thin_wall_options::perturbations_file, BubbleProfiler::logging::Logging_manager::set_minimum_log_level(), BubbleProfiler::solve_perturbative(), BubbleProfiler::solve_shooting(), BubbleProfiler::logging::Trace, BubbleProfiler::Thin_wall_options::use_perturbative, BubbleProfiler::Thin_wall_options::verbose, BubbleProfiler::write_action(), and BubbleProfiler::write_profile().